package com.springboot.controller;

import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.io.IOException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.springboot.User;
import com.springboot.UserRepository;

import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

//import com.springboot.service.AmazonClient;

@Controller
public class HandleController {

   //private AmazonClient amazonClient;
   // @Autowired
   //    HandleController(AmazonClient amazonClient) {
   //          this.amazonClient = amazonClient;
   //    }

   @Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

   @RequestMapping("/")
   public String index() {
      return "index";
   }

   @RequestMapping(value="/upload",method=RequestMethod.POST)
   public String uploadExcelFiles(@RequestParam(value="fileName") MultipartFile[] files, Model model) throws IllegalStateException, IOException {
	         int sz=0;
	         //String saveDirectory = "/home/ubuntu/Desktop/";
	         List<String> fileNames = new ArrayList<String>();

	         //this.amazonClient.uploadFile(files);
	         User u = new User();
	         for(MultipartFile readExcelDataFile : files)
	             {  

	             	XSSFWorkbook workbook = new XSSFWorkbook(readExcelDataFile.getInputStream());
					XSSFSheet worksheet = workbook.getSheetAt(0);
				    
				    for(int i=0;i<worksheet.getPhysicalNumberOfRows()-1 ;i++) {
				        XSSFRow row = worksheet.getRow(i);
				        u.setName(row.getCell(0).getStringCellValue());
				        u.setEmail(row.getCell(1).getStringCellValue());
				    
		     		}

	             	String filename=readExcelDataFile.getOriginalFilename();
		             //mp.transferTo(new File(saveDirectory + filename));
		            fileNames.add(filename);
		            ++sz;
	            }
	            userRepository.save(u);
	         model.addAttribute("sz", sz);
	         model.addAttribute("files",fileNames);
	         return "uploadedFile";
      }

    @GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}


   }
