amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAJ24NPGB4EKPUM5IQ
  secretKey: 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
  bucketName: rajasthan-files
server:
  port: 9000